import {
  ayam,
  bola,
  cacing,
  domba,
  emas,
  foto,
  gajah,
  harimau,
  ikan,
  jagung,
  kunci,
  lumba,
  mangga,
  naga,
  otak,
  rumah,
  sapi,
  tikus,
  panda,
  ular,
  vas,
  wajan,
  yoyo,
  zebra,
} from "../assets/gif";

export const items = [
  { name: "Ayam", gif: ayam },
  { name: "Bola", gif: bola },
  { name: "Cacing", gif: cacing },
  { name: "Domba", gif: domba },
  { name: "Emas", gif: emas },
  { name: "Foto", gif: foto },
  { name: "Gajah", gif: gajah },
  { name: "Harimau", gif: harimau },
  { name: "Ikan", gif: ikan },
  { name: "Jagung", gif: jagung },
  { name: "Kunci", gif: kunci },
  { name: "Lumba", gif: lumba },
  { name: "Mangga", gif: mangga },
  { name: "Naga", gif: naga },
  { name: "Otak", gif: otak },
  { name: "Rumah", gif: rumah },
  { name: "Sapi", gif: sapi },
  { name: "Tikus", gif: tikus },
  { name: "Panda", gif: panda },
  { name: "Ular", gif: ular },
  { name: "Vas", gif: vas },
  { name: "Wajan", gif: wajan },
  { name: "Yoyo", gif: yoyo },
  { name: "Zebra", gif: zebra },
];
